### ISSUE TITLE
Agent: png extension but jpg format, please check

### ISSUE THREAD

**Issue by Gordon-Dry** [Mark-Kerbin/Kerbal-Academy-Contract-Pack#19]
Agent\KerbalAcademy.png
Agent\KerbalAcademy_scaled.png

And the is also a Agent\KerbalAcademy_Scaled.png -> "s" vs. "S"

**Comment by Mark-Kerbin** [comment]
Files converted to jpg after further investigation

s corrected to S

Thanks

**Comment by Gordon-Dry** [comment]
Huh?

I guess you misunderstood me.

The file extension .png is correct.

The files I mentioned above have the extension .png but in real they're jpeg.
That offen happens when using the so-higly-praised Photoshop ...

I just wanted to tell you to save them as real .png files.

**Comment by Mark-Kerbin** [comment]
...
I’m sorry. Probably should not have read this 30 minutes after waking up.
Let’s try that again...

**Comment by Mark-Kerbin** [comment]
Should be png now. Can you check the pull request to make sure I’m not
insane?

**Comment by Gordon-Dry** [comment]
I did.

Photoshop is dumb.

You not only have to choose the extension, you have to tell the programm to really USE that file format.

It's like when saving a Word Document as .txt ...

**Comment by Mark-Kerbin** [comment]
Issue Solved

**Comment by Mark-Kerbin** [comment]
Problem Solved
